#-------------------------------
# General Site Settings
baseURL = "https://fgcode.netlify.app/"
languageCode = "en-us"
title = "Avenco"
googleAnalytics = "" # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Pagination settings:

# For Hugo versions 0.128.0 and above, use the following settings:
# This will set the number of items per page for newer versions.
[pagination]
  pagerSize = 6

# For Hugo versions below 0.128.0, uncomment the line below and comment out the [pagination] block above:
#paginate = 6 # Sets the number of items per page for older versions.


[params]
  logo = "/images/logo.png" # You can add own logo. For example "/images/logo.png".
  description = "Software Engineer expert in AEM, HTML, CSS, JS, PHP, MySQL, ReactJS. "
  enableSearch = true


[params.global.image]
  enable = true
  cover__image = '/images/background.svg' # Add global cover image (This field adds a background to the top and bottom of the site.)

#-------------------------------
# Main Menu
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 2

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/posts/"
    weight = 3
    hasChildren = true

      [[menu.main]]
   #   parent = "Pages"
      name = "About"
      url = "/about/"
      weight = 4

  #    [[menu.main]]
  #    parent = "Pages"
  #    name = "Elements"
  #    url = "/elements/"
  #    weight = 2

  # Call to action button
  [params.menu.button]
    cta__button__text = "Send me a Whatsapp"


  #-------------------------------
  # Author Settings
  [params.author]
    author__name = "Fabian Gonzalez"
    author__title = "👋 Hello I'm Fabian Gonzalez"
    author__bio = "I'm a Software Engineer specialized in AEM, HTML, CSS, JavaScript, PHP, MySQL, and ReactJS.build fast, accessible, and creative web experiences with clean and modern code. Passionate about technology, education, and pushing digital ideas to life. 🤓"
    author__image = "/images/600x600.png"
    author__avatar = "/images/200x200.png"
    button__text = "See my works"


  #-------------------------------
  # Projects Settings
  [params.projects]
    enable = true
    projects__title= "Latest <span class='text-span'>Works</span>" # Add a 'text-span' class to highlight text.
    projects__description= "Here you can explore a selection of my latest projects and case studies.  Each one is crafted with attention to detail, simplicity, and creativity."


  #-------------------------------
  # Testimonials Section
  [params.testimonials]
    enable = true
    testimonial__title = "Work <span class='text-span'>Testimonials</span>" # Add a 'text-span' class to highlight text.
    testimonial__description = "Words from clients and companies I've collaborated with. From development to consulting, here’s what they say about working with me:"

  [[params.testimonial_item]]
    name = " Jorge Rannin"
    image = "/images/250x250_testimonials_georgie.png"
    designation = "Consultant Marketing Specialist"
    content = "Fabian was a pleasure to work with, he managed and created AEM Cloud consultancies for the Colgate and Palmolive team."

  [[params.testimonial_item]]
    name = "Luis Luchessi"
    image = "/images/250x250_testimonials_luis.png"
    designation = "Creator of digital properties"
    content = "Working with Fabian was an incredible experience for our digital platform, he is an exceptional professional who created a modern ecommerce system for us."

  [[params.testimonial_item]]
    name = "Roger Bergson"
    image = "/images/250x250_testimonials_roger.png"
    designation = "CEO, Founder"
    content = "Fabian met all deadlines and delivered a flawless multilingual website. His attention to detail and professionalism are second to none."


  #-------------------------------
  # Blog Section
  [params.blog]
    enable = true
    blog__title = "Recent <span class='text-span'>Blog</span> Posts" # Add a 'text-span' class to highlight text.
    blog__description = ""


  #-------------------------------
  # Contact Settings
  [params.contact]
    enable = true
    contact__email = "your@email.com" # Add your form_id
    contact__title = "<span class='text-span'>Get</span> in touch" # Add a title to your form
    contact__description = "Avenco comes with a built-in contact form." # Add a description to your form

    # NOTE
    # Avenco comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.


  #-------------------------------
  # Newsletter Settings
  [params.mailchimp]
    enable = true
    mailchimp__title = "Contact me via <span class='text-span'>Whatsapp</span> " # Add your title
    mailchimp__text = "To talk about your project, Works, Courses, IT Consulting" # Add descriptions to the form. If you want to use more than one sentence, be sure to separate them with a comma.
    mailchimp__identifier = "gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp" # Add your MailChimp form identifier. For example - gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp
    mailchimp__button__text = "Send me a Whatsapp" # Add your button text

  #-------------------------------
  # Comment Section (Disqus)
  [params.disqus]
    enable = true
    disqusShortname = "anvodstudio-demo" # Add your shortname for Disqus Comment. For example anvodstudio-demo


  #-------------------------------
  # Footer Settings
  # Social Links
  [[params.social]]
    icon = "ion-logo-twitter"
    name = "Twitter"
    link = "https://twitter.com"

  [[params.social]]
    icon = "ion-logo-github"
    name = "Github"
    link = "https://github.com"

  [[params.social]]
    icon = "ion-logo-pinterest"
    name = "Pinterest"
    link = "https://pinterest.com"

  [[params.social]]
    icon = "ion-logo-codepen"
    name = "Codepen"
    link = "https://codepen.io"

  [[params.social]]
    icon = "ion-logo-vimeo"
    name = "Vimeo"
    link = "https://vimeo.com"

  [[params.social]]
    icon = "ion-logo-youtube"
    name = "Youtube"
    link = "https://youtube.com"

  # Example of adding a new link to the footer section:
  # [[params.social]]
  #   icon = "ion-logo-facebook"
  #   name = "Facebook"
  #   link = "https://facebook.com"

  # Other icons can be found at https://ionicons.com/v4/


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[markup.highlight]
  codeFences = true
  guessSyntax = true
  noClasses = false